DROP TABLE IF EXISTS recipes;

CREATE TABLE recipes (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	title TEXT NOT NULL,
	ingredients TEXT NOT NULL,
	guide TEXT NOT NULL,
	servings TEXT NOT NULL
);
